eclipse-ee4j/metro-jax-ws

jaxws-ri/rt/src/main/java/com/sun/xml/ws/model/AbstractWrapperBeanGenerator.java, jaxws-ri/tools/wscompile/src/test/java/com/sun/tools/ws/test/processor/modeler/annotation/NillableArrayTest.java, jaxws-ri/tools/wscompile/src/test/java/com/sun/tools/ws/test/processor/modeler/annotation/NillableTest.java, jaxws-ri/tools/wscompile/src/test/java/com/sun/tools/ws/test/processor/modeler/annotation/NillableTestWs.java
The issue here is that when an element is of an array type, the software currently sets nillable to true regardless of the value of the related annotation. A customer has complained that nillable="false" should be allowed for such a type.
Since the current behavior was specifically placed in the code, there may be a good reason for it, and we do not want to break compatibility.
Therefore, we are adding a new system property -Dcom.sun.xml.ws.jaxb.allowNonNillableArray=true to implement the behavior requested by the customer.
Added testcase at
./jaxws-ri/tools/wscompile/src/test/java/com/sun/tools/ws/test/processor/modeler/annotation/NillableArrayTest.java
./jaxws-ri/tools/wscompile/src/test/java/com/sun/tools/ws/test/processor/modeler/annotation/NillableTest.java
=> Bug28773106branch

jaxws-ri/rt/src/main/java/com/sun/xml/ws/util/xml/XMLStreamWriterFilter.java, jaxws-ri/rt/src/test/java/com/sun/xml/ws/message/saaj/SAAJMessageTest.java
When the SAAJ message contains unusual characters then it gives unexpected partial response 
due to following woodstox exception
Caused by: com.ctc.wstx.exc.WstxIOException: Invalid white space character
(0x3) in text to output (in xml 1.1, could output as a character entity)
So in the fix I have encoded all unusual characters which can give those exceptions
Added testcase method testWhiteSpaceCharacters() at 
./jaxws-ri/rt/src/test/java/com/sun/xml/ws/message/saaj/SAAJMessageTest.java
=> Bug29851244branch

jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/WebServiceAP.java
Added `com.sun.tools.ws.WebServiceAP` as a shortcut for `com.sun.tools.ws.processor.modeler.annotation.WebServiceAp` which is hard to remember and too long to write be it on the command line or in a configuration file of a build tool.
=> Shorten the name of the annotation processor

.gitignore, jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/processor/modeler/annotation/WebServiceWrapperGenerator.java, jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/FilerCodeWriter.java, jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/Options.java
When annotation processor is run directly ie through javac using maven-compiler-plugin, empty directories representing package structure of files to be generated gets created under `${project.basedir}` which is wrong. Problem is that the call to `DirectoryUtil.getOutputDirectoryFor` always creates non-existing dirs. Solution is to start tracking to be created files at the point they are actually created (by `FilerCodeWriter`) instead of  right after the name of the to be created file becomes known.
=> Avoid creating empty directories in unexpected locations by wsgen

jaxws-ri/boms/bom/pom.xml, jaxws-ri/bundles/jaxws-rt/src/main/java/module-info.java, jaxws-ri/extras/eclipselink_jaxb/pom.xml, jaxws-ri/extras/eclipselink_jaxb/src/test/java/com/sun/xml/ws/base/DummyAnnotations.java, jaxws-ri/extras/eclipselink_jaxb/src/test/java/com/sun/xml/ws/base/InVmWSDLResolver.java, jaxws-ri/extras/eclipselink_jaxb/src/test/java/com/sun/xml/ws/base/WsDatabindingTestBase.java, jaxws-ri/extras/eclipselink_jaxb/src/test/java/com/sun/xml/ws/cts/dl_swa/SwaMimeAttachmentTest.java, jaxws-ri/extras/eclipselink_jaxb/src/test/java/com/sun/xml/ws/cts/jws_webparam1/WebParamTest.java, jaxws-ri/extras/eclipselink_jaxb/src/test/java/com/sun/xml/ws/jaxbri/JAXBRIBasicTest.java, jaxws-ri/extras/eclipselink_jaxb/src/test/java/com/sun/xml/ws/test/BasicDatabindingTestBase.java, jaxws-ri/extras/eclipselink_jaxb/src/test/java/com/sun/xml/ws/test/DatabindingTest.java, jaxws-ri/extras/eclipselink_sdo/pom.xml, jaxws-ri/extras/transports/local/src/main/java/module-info.java, jaxws-ri/pom.xml, jaxws-ri/runtime/rt-fi/src/main/java/module-info.java, jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/assembler/MetroTubelineAssembler.java, jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/assembler/TubeCreator.java, jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/assembler/TubelineAssemblyController.java, jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/model/Injector.java, jaxws-ri/runtime/rt/src/main/java/module-info.java
* added missing exports to JPMS descriptors
* updated gmbal, pfl and policy versions
* removed obsolete code from poms
=> improve JPMS support

jaxws-ri/bundles/jaxws-ri/src/main/resources/bin/wsgen.sh
wsimport.sh it working fine. The issue is happening in wsgen.sh.
> jbescos@JBESCOS-CZ /cygdrive/c/workspaceJAXB/metro-jax-ws/jaxws-ri/bundles/jaxws-ri/src/main/resources/bin
> $ ./wsgen.sh
> ./wsgen.sh: line 57: exec: C:\Program: not found
Now it will be success with that error:
> jbescos@JBESCOS-CZ /cygdrive/c/workspaceJAXB/metro-jax-ws/jaxws-ri/bundles/jaxws-ri/src/main/resources/bin
> $ ./wsgen.sh
> Error: Could not find or load main class com.sun.tools.ws.WsGen
=> wsgen.sh fix for JAVA_HOME variables with spaces

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/api/message/saaj/SaajStaxWriter.java, jaxws-ri/runtime/rt/src/test/java/com/sun/xml/ws/message/saaj/SAAJFactoryTest.java
In 2017, Aleks Efimov put in a fix for to the javaee/metro-saaj repository to fix a problem where namespace declarations were getting added to parent elements incorrectly (JDK-8186441). This fix seems to have gotten lost in the eclipse-ee4j/metro-jax-ws repository, so this change is just to re-apply the fix.
For details see:
http://openjdk.5641.n7.nabble.com/10-RFR-8186441-Change-of-behavior-in-the-getMessage-method-of-the-SOAPMessageContextImpl-class-td320585.html
and the original pull request:
https://github.com/javaee/metro-saaj/pull/92/commits/8267e08a8a26138f0223bb86dfe599e69f0af28d
Signed-off-by: Brian Delaney <briandelaney@google.com>
=> Re-apply source fix for JDK-8186441

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/assembler/MetroConfigLoader.java
Fix for [https://github.com/eclipse-ee4j/metro-jax-ws/issues/95](https://github.com/eclipse-ee4j/metro-jax-ws/issues/95)
torstenwerner put this fix in old repository to get rid of the problem, where "getResource" method from private nested class (used in Tomcat) is called by reflection
=> JAX_WS-1175: Issue #95 - fix method call by reflection

jaxws-ri/bundles/jaxws-rt/pom.xml
=> import of jdk specific class must be optional in osgi

jaxws-ri/runtime/policy/pom.xml
=> make sure policy builds sources jar by default

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/wsdl/writer/WSDLPatcher.java, jaxws-ri/runtime/rt/src/test/java/com/sun/xml/ws/wsdl/writer/PublishWSDLTest.java, jaxws-ri/runtime/rt/src/test/java/com/sun/xml/ws/wsdl/writer/PublishWSDLTestWs.java
The schemaLocation of the xsd import in the wsdl generated by JAXWS-RI 
is replaced by the actual host:port URL of the server where the webservice is deployed
This is how webservice is designed but the customer has a requirement where they do not 
want the absolute location of the schemaLocation to be replaced by host:port URL of the server
Therefore, we are adding a new system property -Dcom.sun.xml.ws.wsdl.externalSchemaLocationURL=true 
to implement the behavior requested by the customer
Added testcase at
./jaxws-ri/runtime/rt/src/test/java/com/sun/xml/ws/wsdl/writer/PublishWSDLTestWs.java
./jaxws-ri/runtime/rt/src/test/java/com/sun/xml/ws/wsdl/writer/PublishWSDLTest.java
=> Bugno31091695

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/streaming/XMLStreamReaderUtil.java, jaxws-ri/runtime/rt/src/test/java/com/sun/xml/ws/streaming/XMLReaderCompositeTest.java
Relates to this issue: https://github.com/eclipse-ee4j/metro-jax-ws/issues/156
=> SOAP JAX-WS VERBOSE ERROR MESSAGES

jaxws-ri/runtime/rt/src/main/java-mr/9/com/sun/xml/ws/util/AuthUtil.java, jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/developer/JAXWSProperties.java, jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/transport/http/client/HttpClientTransport.java, jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/util/AuthUtil.java
Author: Nancy Bosecker <nbosecker@gmail.com>
Date: Fri Sept 18 16:24:00 2020
For Java 9+, allow clients to set an authenticator on HttpURLConnection class, which allows clients to avoid use of the default Authenticator whose cache is hidden and cannot be cleared. See https://bugs.openjdk.java.net/browse/JDK-8169495
Signed-off-by: Nancy Bosecker <nbosecker@gmail.com>
=> Expose setAuthenticator method of HttpURLConnection for Java 9+

jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/processor/modeler/wsdl/WSDLModeler.java, jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/WsimportTool.java, jaxws-ri/tools/wscompile/src/main/resources/com/sun/tools/ws/resources/modeler.properties
A Remote Code Execution was reported in Payara, achieved via a Host Header attack of the Webservice Tester servlet which gets loaded on deployment of a JAX-WS application.
The Host Header attack was fixed in the servlet, but for completeness we also looked into fixing the RME too.
In the example given to us, the RME comes in from a custom parameter name binding not being validated or sanitised, leading to the parameter getting replaced with malicious code. Specifically in the example given to us (but not necessarily limited to this), the parameter name in the javadoc of the method gets replaced with malicious code.
I took the leap, based on the current validation, that a custom name needs to be a valid Java variable (no spaces, no "/*" to start a comment, etc.), so I added in validation …
=> Validate Custom Name

jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/processor/modeler/wsdl/WSDLModeler.java, jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/WsimportTool.java, jaxws-ri/tools/wscompile/src/main/resources/com/sun/tools/ws/resources/modeler.properties
Backport of https://github.com/eclipse-ee4j/metro-jax-ws/pull/221
A Remote Code Execution was reported in Payara, achieved via a Host Header attack of the Webservice Tester servlet which gets loaded on deployment of a JAX-WS application.
The Host Header attack was fixed in the servlet, but for completeness we also looked into fixing the RME too.
In the example given to us, the RME comes in from a custom parameter name binding not being validated or sanitised, leading to the parameter getting replaced with malicious code. Specifically in the example given to us (but not necessarily limited to this), the parameter name in the javadoc of the method gets replaced with malicious code.
I took the leap, based on the current validation, that a custom name needs to be a valid Java variable (no …
=> Validate Custom Name (EE8)

jaxws-ri/docs/release-documentation/src/main/docbook/changelog.xml, jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/transport/http/HttpAdapter.java
=> #250: Spell dumpThreshold correctly, keeping misspelled legacy option dumpTreshold as a fallback

.github/workflows/maven.yml, jaxws-ri/docs/release-documentation/src/main/docbook/changelog.xml, jaxws-ri/docs/release-documentation/src/main/docbook/overview.xml, jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/api/server/ThreadLocalContainerResolver.java, jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/server/SDDocumentImpl.java
=> docs updates, test env updates, fix for #98

jaxws-ri/docs/release-documentation/src/main/docbook/release-notes.xml
Document the issue in the release notes
=> #594: JAX WS builtin Server implementation is very slow on Linux

jaxws-ri/docs/release-documentation/src/main/docbook/changelog.xml, jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/encoding/MimeCodec.java, jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/encoding/MtomCodec.java, jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/message/saaj/SAAJMessage.java
=> #582: JAX-WS write Content-ID: header with small 'd' letter and without a space after ':' for MIME Attachment part

jaxws-ri/docs/release-documentation/src/main/docbook/changelog.xml, jaxws-ri/docs/release-documentation/src/main/docbook/jax-ws-ri-extensions.xml, jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/fault/SOAPFaultBuilder.java, jaxws-ri/runtime/rt/src/test/java/com/sun/xml/ws/fault/SOAPFaultBuilderTest.java
The faultstring in the SOAPFault contains the exception message if any which is the default current behavior
The customer has a requirement where they do not want any exception messages to be displayed in the faultstring for security concerns of exposing class
Therefore, we are adding a new system property -Dcom.sun.xml.ws.fault.doNotPrintExpMsg=true
to implement the behavior requested by the customer
Added testcase at 
./jaxws-ri/runtime/rt/src/test/java/com/sun/xml/ws/fault/SOAPFaultBuilderTest.java
=> Bugno34600318

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/fault/SOAP11Fault.java, jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/fault/SOAP12Fault.java, jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/fault/SOAPFaultBuilder.java, jaxws-ri/runtime/rt/src/test/java/com/sun/xml/ws/fault/SOAPFaultBuilderTest.java
As of now, SOAP response packet contains faultString which contains detailed error message in case of any SOAP Fault.
The customer has a requirement where they do not want any exception messages to be displayed in the faultString for security concerns.
For the same reason, a fix was introduced for BUG34600318 where a new system property com.sun.xml.ws.fault.SOAPFaultBuilder.captureExceptionMessage=false
has been added to simulate customer intended behavior.
This bug is intended to address the same issue but to include all possible cases which has been missed in the previous BUG34600318.
Added more testcases in file:
./jaxws-ri/runtime/rt/src/test/java/com/sun/xml/ws/fault/SOAPFaultBuilderTest.java
Signed-off-by: Himanshu Ranjan <himanshu.ranjan@oracle.com>
=> BUG 35047999: Show Server Error in faultString instead of error details.

jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/processor/modeler/wsdl/WSDLModeler.java
Removed warning about SOAP 1.2 being non-standard when SOAP 1.2 extensions are enabled. 
SOAP 1.2 (https://www.w3.org/TR/soap12-part1/ ) was released over a decade ago in 2007  and is no longer considered non-standard. In order to use soap 1.2 features the soap 1.2 extension mode must be explicitly enabled, so wsimport should not give warnings that the user is using SOAP 1.2 features.
=> Removed obselete warning about non-standard soap 1.2

jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/processor/modeler/wsdl/WSDLModeler.java
We were discussing this @lukasj and me by zoom and he asked me to revert this because the warning is currently correct since the xml-ws spec considers SOAP 1.2 as to be supported in the future (see https://jakarta.ee/specifications/xml-web-services/4.0/jakarta-xml-ws-spec-4.0#goals ) and is currently optional (search through the spec for "SOAP 1.2" to learn more).
acceptable form of this change can be:
- full update through the XML-WS spec as well as the implementation and addition of new TCKs
or
- addition of an option to suppress warnings like this, instead of forcing it.
PR was: https://github.com/eclipse-ee4j/metro-jax-ws/pull/700
=> Revert:  Removed obselete warning about non-standard soap 1.2 #700 
