jaxws-ri/rt/src/main/java/com/sun/xml/ws/api/message/saaj/SAAJFactory.java
jaxws-ri/rt/src/test/java/com/sun/xml/ws/message/saaj/SAAJFactoryTest.java

Signed-off-by: monicadragomir <monica.dragomir@oracle.com>

https://github.com/eclipse-ee4j/metro-jax-ws/issues/7

---

jaxws-ri/boms/bom-ext/pom.xml
jaxws-ri/boms/bom/pom.xml

integrate recent jakarta updates

---

jaxws-ri/boms/bom-ext/pom.xml
jaxws-ri/boms/bom/pom.xml

integrate recent jakarta updates (#13)

---

jaxws-ri/bundles/jaxws-rt/runtime/src/main/java/module-info.java
jaxws-ri/bundles/jaxws-tools/tools/src/main/java/module-info.java
jaxws-ri/rt/src/main/java/module-info.java
jaxws-ri/servlet/src/main/java/module-info.java
jaxws-ri/tools/wscompile/src/main/java/module-info.java
jaxws-ri/tools/wscompile/src/test/java/module-info.java

fix mod name

---

jaxws-ri/boms/bom/pom.xml
jaxws-ri/bundles/jaxws-rt/runtime/src/main/java/module-info.java
jaxws-ri/rt/src/main/java/module-info.java
jaxws-ri/tools/wscompile/src/main/java-mr/com/sun/tools/ws/ant/WsGen.java
jaxws-ri/tools/wscompile/src/main/java-mr/com/sun/tools/ws/ant/WsImport.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/ant/WsTask2.java

adopt gmbal, test fixes

---

jaxws-ri/bundles/jaxws-rt/runtime/pom.xml
jaxws-ri/bundles/jaxws-tools/tools/pom.xml

versioned sources are in wrong location

---

jaxws-ri/bundles/jaxws-rt/runtime/pom.xml
jaxws-ri/bundles/jaxws-rt/runtime/src/main/java/module-info.java
jaxws-ri/rt/pom.xml
jaxws-ri/rt/src/main/java/module-info.java

Signed-off-by: Roman Grigoriadi <roman.grigoriadi@oracle.com>

JPMS service loader provider for runtime.

---

jaxws-ri/bundles/jaxws-rt/runtime/pom.xml
jaxws-ri/bundles/jaxws-rt/runtime/src/main/java/module-info.java
jaxws-ri/rt/pom.xml
jaxws-ri/rt/src/main/java/module-info.java

Signed-off-by: Roman Grigoriadi <roman.grigoriadi@oracle.com>

JPMS service loader jaxws runtime.

---

jaxws-ri/boms/bom-ext/pom.xml

integrate eclipselink 2.7.4

---

jaxws-ri/rt/src/main/java/com/sun/xml/ws/client/WSServiceDelegate.java
jaxws-ri/rt/src/test/java/com/sun/xml/ws/client/WSServiceDelegateTest.java

Signed-off-by: monicadragomir <monica.dragomir@oracle.com>

https://github.com/eclipse-ee4j/metro-jax-ws/issues/32

---

jaxws-ri/boms/bom/pom.xml

fix reference to the JWS API source bundle

---

jaxws-ri/pom.xml

update the build for jdk 11.0.2

---

jaxws-ri/boms/bom-ext/pom.xml
jaxws-ri/rt/pom.xml
jaxws-ri/rt/src/main/java/com/sun/xml/ws/model/WrapperBeanGenerator.java

update internally used ASM to version 7.1 and bump internally generated bytecode to v1_8

update asm to 7.1

---

jaxws-ri/rt/src/main/java/com/sun/xml/ws/api/streaming/ContextClassloaderLocal.java
jaxws-ri/rt/src/test/java/com/sun/xml/ws/api/streaming/ContextClassloaderLocalTest.java

…EBSERVICES
Signed-off-by: monicadragomir <monica.dragomir@oracle.com>

https://github.com/eclipse-ee4j/metro-jax-ws/issues/61

---

jaxws-ri/rt/src/main/java/com/sun/xml/ws/policy/jaxws/XmlWsLoggingProvider.java
jaxws-ri/rt/src/main/java/module-info.java
jaxws-ri/rt/src/main/resources/META-INF/services/com.sun.xml.ws.policy.spi.LoggingProvider

adopt changes in policy

---

jaxws-ri/boms/bom/pom.xml

Remove temporary repos

---

.travis.yml
README.md

add travis config

---

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/server/SDDocumentImpl.java

fix project URL in published documents

---

jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/package-info.java
jaxws-ri/tools/wscompile/src/test/java/com/sun/tools/ws/test/ant/WsGenTaskTest.java
jaxws-ri/tools/wscompile/src/test/java/com/sun/tools/ws/test/ant/WsImportTaskTest.java
jaxws-ri/tools/wscompile/src/test/resources/com/sun/tools/ws/test/ant/resources/wsgen.xml
jaxws-ri/tools/wscompile/src/test/resources/com/sun/tools/ws/test/ant/resources/wsimport.xml

allow build on jdk13

---

jaxws-ri/boms/bom-ext/pom.xml
jaxws-ri/bundles/jaxws-rt/pom.xml
jaxws-ri/bundles/jaxws-tools/pom.xml
jaxws-ri/bundles/jaxws-tools/src/main/java/module-info.java
jaxws-ri/extras/eclipselink_jaxb/pom.xml
jaxws-ri/extras/eclipselink_sdo/pom.xml
jaxws-ri/extras/transports/async-client-transport/pom.xml
jaxws-ri/extras/transports/local/pom.xml
jaxws-ri/pom.xml
jaxws-ri/tools/wscompile/pom.xml
jaxws-ri/tools/wscompile/src/main/java/module-info.java

Update dependencies, osgi headers, JPMS definitions

---

jaxws-ri/boms/bom/pom.xml

Integrate JAXB-RI 2.3.3-b02

---

jaxws-ri/rt/src/main/java/com/sun/xml/ws/binding/BindingImpl.java

Signed-off-by: Jan Supol <jan.supol@oracle.com>

Removed "internal" package for 2.3.2

---

jaxws-ri/bundles/jaxws-rt/pom.xml
jaxws-ri/bundles/jaxws-tools/pom.xml
jaxws-ri/bundles/pom.xml
jaxws-ri/docs/pom.xml
jaxws-ri/docs/release-documentation/pom.xml
jaxws-ri/docs/samples/pom.xml
jaxws-ri/docs/www/pom.xml
jaxws-ri/extras/eclipselink_jaxb/pom.xml
jaxws-ri/extras/eclipselink_sdo/pom.xml
jaxws-ri/extras/pom.xml
jaxws-ri/extras/transports/async-client-transport/pom.xml
jaxws-ri/extras/transports/local/pom.xml
jaxws-ri/pom.xml
jaxws-ri/runtime/httpspi-servlet/pom.xml
jaxws-ri/runtime/pom.xml
jaxws-ri/runtime/rt-fi/pom.xml
jaxws-ri/runtime/rt/pom.xml
jaxws-ri/runtime/servlet/pom.xml
jaxws-ri/tests/jaxwsTestUtil/pom.xml
jaxws-ri/tests/unit-rearch/pom.xml
jaxws-ri/tools/pom.xml
jaxws-ri/tools/wscompile/pom.xml

update build plugins, prepare for release

---

jaxws-ri/boms/bom/pom.xml

Integrate saaj 1.5.2

---

jaxws-ri/extras/jaxws-maven-plugin/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/src/it/wsgen/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/src/it/wsimport/file/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/src/it/wsimport/url/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/src/test/it/parent/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/src/test/it/wsimport22/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/src/test/java/org/jvnet/jax_ws_commons/jaxws/WsImportMojoITCase.java

Remove (obsolete) optional dependency on jaxb2-basics

---

jaxws-ri/extras/jaxws-maven-plugin/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/src/site/apt/examples/using-binding-files.apt
jaxws-ri/extras/jaxws-maven-plugin/src/site/apt/examples/using-jaxb-plugins.apt
jaxws-ri/extras/jaxws-maven-plugin/src/site/apt/examples/using-jaxws22-on-jdk6.apt
jaxws-ri/extras/jaxws-maven-plugin/src/site/apt/examples/using-metro.apt
jaxws-ri/extras/jaxws-maven-plugin/src/site/apt/examples/using-snapshots.apt
jaxws-ri/extras/jaxws-maven-plugin/src/site/apt/examples/using-wsdlLocation.apt
jaxws-ri/extras/jaxws-maven-plugin/src/site/apt/examples/using-wstools-from-jdk.apt
jaxws-ri/extras/jaxws-maven-plugin/src/site/apt/index.apt
jaxws-ri/extras/jaxws-maven-plugin/src/site/apt/usage.apt
jaxws-ri/extras/jaxws-maven-plugin/src/site/site.xml

update documentation for maven plugin

---

jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/Invoker.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/ant/WsTask2.java

replace javax leftovers

---

jaxws-ri/boms/bom-ext/pom.xml
jaxws-ri/bundles/jaxws-ri/pom.xml
jaxws-ri/extras/eclipselink_jaxb/pom.xml
jaxws-ri/extras/eclipselink_jaxb/src/test/java/com/sun/xml/ws/jaxbri/JAXBRIBasicTest.java
jaxws-ri/extras/eclipselink_sdo/pom.xml
jaxws-ri/extras/pom.xml

adopt eclipselink 3.0.0-M1

---

jaxws-ri/bundles/jaxws-rt/pom.xml
jaxws-ri/runtime/rt/pom.xml

Mail should be there for runtime

---

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/spi/db/BindingContext.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/spi/db/BindingContextFactory.java
jaxws-ri/runtime/rt/src/test/java/com/sun/xml/ws/spi/db/BindingContextFactoryTest.java

adopt jaxb-ri split in databinding

---

jaxws-ri/boms/bom/pom.xml
jaxws-ri/bundles/jaxws-rt/pom.xml
jaxws-ri/bundles/jaxws-rt/src/main/java/module-info.java
jaxws-ri/runtime/rt/pom.xml
jaxws-ri/runtime/rt/src/main/java/module-info.java
jaxws-ri/tests/unit/pom.xml

Integrate management-api:3.2.3, gmbal-api-only:4.0.2

---

jaxws-ri/tests/pom.xml
jaxws-ri/tests/unit/pom.xml

Re-enable tests

---

jaxws-ri/extras/jaxws-maven-plugin/src/site/apt/examples/using-snapshots.apt

fix wording in snapshots how to

---

jaxws-ri/boms/bom/pom.xml

Integrate xml.ws-api 3.0.0-RC3

---

jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/WsimportTool.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/plugin/at_generated/PluginImpl.java
jaxws-ri/tools/wscompile/src/main/resources/com/sun/tools/ws/resources/wscompile.properties

Update mark-generated wsimport plugin

---

jaxws-ri/extras/eclipselink_sdo/pom.xml
jaxws-ri/extras/eclipselink_sdo/src/main/java/module-info.java

re-enable tests for sdo databinding plugin

---

jaxws-ri/boms/bom/pom.xml
jaxws-ri/tests/unit/pom.xml

Integrate jaxb-ri 3.0.0-M4

---

jaxws-ri/tests/unit/testcases/bugs/jaxws1044/server/CookieAService.java
jaxws-ri/tests/unit/testcases/provider/servlet_parameter_507/server/HelloImpl.java
jaxws-ri/tests/unit/testcases/server/http_multi_cookie_servlet/server/HelloServiceImpl.java
jaxws-ri/tests/unit/testcases/server/http_only/server/HelloServiceImpl.java
jaxws-ri/tests/unit/testcases/server/session_ignorecase_834/server/HelloServiceImpl.java

fix forgotten references to javax.servlet

---

jaxws-ri/boms/bom-ext/pom.xml

Integrate mail 2.0.0-RC6

---

README.md

add pointer to the changelog

---

jaxws-ri/boms/bom/pom.xml

Signed-off-by: arjantijms <arjan.tijms@gmail.com>

Update stax to 6.2.1/4.2.1

---

jaxws-ri/bundles/jaxws-rt/src/main/java/module-info.java
jaxws-ri/bundles/jaxws-tools/src/main/java/module-info.java
jaxws-ri/runtime/rt/src/main/java-mr/9/com/sun/xml/ws/util/MrJarUtil.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/assembler/TubelineAssemblyContextImpl.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/util/MrJarUtil.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/util/ServiceFinder.java
jaxws-ri/runtime/rt/src/main/java/module-info.java
jaxws-ri/tools/wscompile/src/main/java-mr/com/sun/tools/ws/util/MrJarUtil.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/processor/generator/JwsImplGenerator.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/processor/generator/ServiceGenerator.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/util/MrJarUtil.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/util/ServiceConfigurationError.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/util/ServiceFinder.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/WsgenOptions.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/WsgenTool.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/WsimportOptions.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/WsimportTool.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wsdl/parser/MetadataFinder.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wsdl/parser/WSDLParser.java
jaxws-ri/tools/wscompile/src/main/java/module-info.java
jaxws-ri/tools/wscompile/src/test/java/module-info.java

Fix service loading on module path/jdk11+

---

jaxws-ri/boms/bom-ext/pom.xml
jaxws-ri/boms/bom/pom.xml
jaxws-ri/bundles/jaxws-ri/src/main/assembly/assembly.xml
jaxws-ri/bundles/jaxws-rt/pom.xml
jaxws-ri/extras/eclipselink_jaxb/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/src/main/java/org/jvnet/jax_ws_commons/jaxws/WsImportMojo.java
jaxws-ri/extras/jaxws-maven-plugin/src/test/it/jaxwscommons-81/src/jaxws/bindings-default.xjc
jaxws-ri/extras/jaxws-maven-plugin/src/test/it/jaxwscommons-81/src/remote-xjc/bindings.xjc
jaxws-ri/extras/jaxws-maven-plugin/src/test/it/jaxwscommons-81/src/test-wsdl/xjc/a.xml
jaxws-ri/extras/jaxws-maven-plugin/src/test/it/jaxwscommons-81/src/test-wsdl/xjc/b.xml
jaxws-ri/extras/jaxws-maven-plugin/src/test/it/metro/src/jaxws/bindings-default.xjc
jaxws-ri/extras/jaxws-maven-plugin/src/test/it/metro/src/remote-xjc/bindings.xjc
jaxws-ri/extras/jaxws-maven-plugin/src/test/it/metro/src/test-wsdl/xjc/a.xml
jaxws-ri/extras/jaxws-maven-plugin/src/test/it/metro/src/test-wsdl/xjc/b.xml
jaxws-ri/extras/jaxws-maven-plugin/src/test/it/wsimport22/src/jaxws/bindings-default.xjc
jaxws-ri/extras/jaxws-maven-plugin/src/test/it/wsimport22/src/remote-xjc/bindings.xjc
jaxws-ri/extras/jaxws-maven-plugin/src/test/it/wsimport22/src/test-wsdl/xjc/a.xml
jaxws-ri/extras/jaxws-maven-plugin/src/test/it/wsimport22/src/test-wsdl/xjc/b.xml
jaxws-ri/pom.xml
jaxws-ri/runtime/policy/pom.xml
jaxws-ri/runtime/rt/pom.xml
jaxws-ri/tests/unit/pom.xml
jaxws-ri/tests/unit/testcases/customization/external/custom-client.xml
jaxws-ri/tests/unit/testcases/customization/external/server/custom-server.xml
jaxws-ri/tests/unit/testcases/customization/indexed_6625158/server/test.xsd
jaxws-ri/tools/wscompile/pom.xml
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/processor/modeler/wsdl/PseudoSchemaBuilder.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wsdl/document/jaxws/JAXWSBindingsConstants.java
jaxws-ri/tools/wscompile/src/test/java/com/sun/tools/ws/test/ant/WsAntToolsTest.java

Integrate latest dependencies

---

jaxws-ri/boms/bom/pom.xml

Integrate jaxb-ri 3.0.0, streambuffer 2.0.1

---

jaxws-ri/bundles/jaxws-rt/src/main/java/module-info.java
jaxws-ri/runtime/rt/src/main/java-mr/9/com/oracle/webservices/api/message/AccessorFactory.java
jaxws-ri/runtime/rt/src/main/java/com/oracle/webservices/api/message/AccessorFactory.java
jaxws-ri/runtime/rt/src/main/java/com/oracle/webservices/api/message/BasePropertySet.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/transport/http/HttpAdapter.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/transport/http/client/HttpTransportPipe.java
jaxws-ri/runtime/rt/src/main/java/module-info.java

switched to methodhandles in PropertySets,
added empty new line after request/response message dump

added missing export,

---

jaxws-ri/runtime/servlet/src/main/java/module-info.java

fix cp year

---

jaxws-ri/runtime/rt/exclude.xml
jaxws-ri/runtime/rt/src/main/java/com/oracle/webservices/api/message/BasePropertySet.java

spotbugs warnings

---

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/api/PropertySet.java
jaxws-ri/tests/unit/testcases/bugs/jaxws1049/client/PropertySetAsMapTest.java

fix failing tests

---

jaxws-ri/docs/release-documentation/src/main/docbook/tools-wsgen-ant-task.xml
jaxws-ri/docs/release-documentation/src/main/docbook/tools-wsgen.xml
jaxws-ri/extras/jaxws-maven-plugin/src/main/java/org/jvnet/jax_ws_commons/jaxws/AbstractWsGenMojo.java
jaxws-ri/extras/jaxws-maven-plugin/src/main/java/org/jvnet/jax_ws_commons/jaxws/MainWsGenMojo.java
jaxws-ri/extras/jaxws-maven-plugin/src/main/java/org/jvnet/jax_ws_commons/jaxws/TestWsGenMojo.java
jaxws-ri/extras/jaxws-maven-plugin/src/main/java/org/jvnet/jax_ws_commons/jaxws/WsdlGenMojo.java
jaxws-ri/extras/jaxws-maven-plugin/src/site/apt/index.apt
jaxws-ri/extras/jaxws-maven-plugin/src/site/resources/release-notes-301.html
jaxws-ri/extras/jaxws-maven-plugin/src/test/it/jaxwscommons-103/ws/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/src/test/it/jaxwscommons-3/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/src/test/java/org/jvnet/jax_ws_commons/jaxws/HelpMojoITCase.java
jaxws-ri/extras/jaxws-maven-plugin/src/test/java/org/jvnet/jax_ws_commons/jaxws/WsImportMojoITCase.java
jaxws-ri/runtime/rt/exclude.xml
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/ant/WsGenBase.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/WsgenOptions.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/WsgenTool.java
jaxws-ri/tools/wscompile/src/main/resources/com/sun/tools/ws/resources/wscompile.properties

wsgen: added ability generate WSDL/Schema files only

---

jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/WsgenTool.java

avoid NPE when reporting errors from wsgen

---

jaxws-ri/runtime/policy/pom.xml
jaxws-ri/runtime/policy/src/main/java/module-info.java
jaxws-ri/runtime/policy/src/test/java/module-info.java
jaxws-ri/runtime/rt/pom.xml
jaxws-ri/runtime/rt/src/main/java/module-info.java
jaxws-ri/tools/wscompile/pom.xml
jaxws-ri/tools/wscompile/src/main/java/module-info.java
jaxws-ri/tools/wscompile/src/test/java/module-info.java

switch to dev-dev mod dependency

---

jaxws-ri/boms/bom-ext/pom.xml
jaxws-ri/boms/bom/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/pom.xml
jaxws-ri/pom.xml
jaxws-ri/runtime/policy/pom.xml
jaxws-ri/runtime/policy/src/main/java/com/sun/xml/ws/policy/sourcemodel/attach/ExternalAttachmentsUnmarshaller.java
jaxws-ri/runtime/policy/src/main/resources/com/sun/xml/ws/policy/privateutil/Localization.properties
jaxws-ri/tools/wscompile/src/main/resources/com/sun/tools/ws/resources/webserviceap.properties

Integrate latest dependencies,

---

jaxws-ri/extras/jaxws-maven-plugin/pom.xml

fix cpright

---

jaxws-ri/boms/bom/pom.xml

integrate jax-ws-api 3.0.1

---

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/api/SOAPVersion.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/api/message/saaj/SAAJMessageHeaders.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/api/message/saaj/SaajStaxWriter.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/api/server/WSEndpoint.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/client/HandlerConfigurator.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/model/AbstractSEIModelImpl.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/model/WrapperBeanGenerator.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/server/WSEndpointImpl.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/server/WSEndpointMOMProxy.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/server/sei/EndpointResponseMessageBuilder.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/transport/Headers.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/transport/http/DeploymentDescriptorParser.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/transport/http/client/InMemoryCookieStore.java

minor housekeeping

---

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/model/AbstractSEIModelImpl.java

Too agressive cleanup :-(

---

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/server/MonitorBase.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/util/FastInfosetUtil.java

limit exception dumps in common/expacted cases

---

jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/WsimportOptions.java

Signed-off-by: Jorge Bescos Gascon <jorge.bescos.gascon@oracle.com>

Copyright fix

---

jaxws-ri/extras/jaxws-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml

Signed-off-by: tvallin <thibault.vallin@oracle.com>

Add Eclipse m2e lifecycle mapping to jaxws-maven-plugin 

---

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/assembler/jaxws/TransportTubeFactory.java

Fix the fallback factory to implement correct interface

---

jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/Invoker.java

avoid npe when starting wstools

---

jaxws-ri/boms/bom/pom.xml

Integrate jaxb-ri 3.0.1-b02

---

jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/plugin/at_generated/PluginImpl.java
jaxws-ri/tools/wscompile/src/test/java/com/sun/tools/ws/test/wscompile/WsimportOptionsTest.java

mark-generated sometimes produces a wrong date value

---

jaxws-ri/boms/bom/pom.xml

Integrate jaxb-impl 3.0.1

---

jaxws-ri/boms/bom/pom.xml

Integrate saaj-impl 2.0.1

---

jaxws-ri/boms/bom/pom.xml
jaxws-ri/bundles/jaxws-rt/src/main/java/module-info.java
jaxws-ri/runtime/rt/pom.xml
jaxws-ri/runtime/rt/src/main/java/module-info.java

Integrate ha-api 3.1.13

---

jaxws-ri/boms/bom/pom.xml

Integrate gmbal 4.0.3

---

jaxws-ri/boms/bom/pom.xml

Integrate streambuffer 1.5.10,

---

jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/processor/modeler/wsdl/WSDLModeler.java
jaxws-ri/tools/wscompile/src/main/resources/com/sun/tools/ws/resources/modeler.properties

Fix copypright years

---

jaxws-ri/extras/helidon-integration/bom/pom.xml
jaxws-ri/extras/helidon-integration/helidon-soap-mp/pom.xml
jaxws-ri/extras/helidon-integration/helidon-soap/pom.xml
jaxws-ri/extras/helidon-integration/java.activation/pom.xml
jaxws-ri/extras/helidon-integration/pom.xml
jaxws-ri/extras/helidon-integration/samples/helidon-soap-demo-mp/pom.xml
jaxws-ri/extras/helidon-integration/samples/helidon-soap-demo/pom.xml
jaxws-ri/extras/helidon-integration/samples/metro-samples/annotations/pom.xml
jaxws-ri/extras/helidon-integration/samples/metro-samples/async/pom.xml
jaxws-ri/extras/helidon-integration/samples/metro-samples/asyncprovider/pom.xml
jaxws-ri/extras/helidon-integration/samples/metro-samples/asyncservice/pom.xml
jaxws-ri/extras/helidon-integration/samples/metro-samples/pom.xml
jaxws-ri/extras/helidon-integration/samples/metro-samples/restful/pom.xml
jaxws-ri/extras/helidon-integration/samples/pom.xml

set proper version

---

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/api/pipe/TubelineAssemblerFactory.java

Improve error message

---

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/server/WSEndpointImpl.java

#226: use deprecated context for backward compatibility

---

jaxws-ri/extras/helidon-integration/bom/pom.xml

use ee4j parent in helidon integration

---

jaxws-ri/extras/helidon-integration/bom/pom.xml
jaxws-ri/extras/helidon-integration/java.activation/pom.xml
jaxws-ri/extras/helidon-integration/se/pom.xml

rename helidion activation

---

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/api/streaming/XMLStreamReaderFactory.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/WsimportOptions.java

#215: WsImport.doMain() not closing binding file upon subsequent invocations

---

jaxws-ri/pom.xml
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/api/message/saaj/SaajStaxWriter.java

 #73: Serialization error when using SOAPHandler and Eclipselink plugin

---

jaxws-ri/pom.xml

revert unintended change

---

jaxws-ri/extras/helidon-integration/mp/src/main/java/module-info.java
jaxws-ri/extras/helidon-integration/pom.xml
jaxws-ri/extras/helidon-integration/samples/se-demo/src/main/java/module-info.java

[helidon] fix build for openjdk

---

jaxws-ri/bundles/jaxws-rt/pom.xml
jaxws-ri/bundles/jaxws-rt/src/main/java/module-info.java
jaxws-ri/extras/eclipselink_jaxb/pom.xml
jaxws-ri/pom.xml
jaxws-ri/runtime/rt/pom.xml
jaxws-ri/runtime/rt/src/main/java-mr/9/com/sun/xml/ws/model/InjectorHelper.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/model/Injector.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/model/InjectorHelper.java
jaxws-ri/runtime/rt/src/main/java/module-info.java
jaxws-ri/tests/pom.xml

closes #55
closes #60 
closes #225

Make injector working on JDK 17

---

jaxws-ri/.github/workflows/maven.yml

setup gh actions

---

jaxws-ri/runtime/rt/src/main/java-mr/9/com/sun/xml/ws/model/InjectorHelper.java

delay warning messages

---

jaxws-ri/extras/helidon-integration/bom/pom.xml
jaxws-ri/extras/helidon-integration/samples/metro-samples/annotations/pom.xml
jaxws-ri/extras/helidon-integration/samples/metro-samples/annotations/src/main/resources/logging.properties
jaxws-ri/extras/helidon-integration/samples/metro-samples/async/pom.xml
jaxws-ri/extras/helidon-integration/samples/metro-samples/async/src/main/resources/logging.properties
jaxws-ri/extras/helidon-integration/samples/metro-samples/asyncprovider/src/main/resources/logging.properties
jaxws-ri/extras/helidon-integration/samples/metro-samples/asyncservice/src/main/resources/logging.properties
jaxws-ri/extras/helidon-integration/samples/metro-samples/restful/src/main/resources/logging.properties
jaxws-ri/extras/helidon-integration/samples/mp-demo/pom.xml
jaxws-ri/extras/helidon-integration/samples/mp-demo/src/main/resources/logging.properties
jaxws-ri/extras/helidon-integration/samples/se-demo/pom.xml
jaxws-ri/extras/helidon-integration/samples/se-demo/src/main/java/module-info.java
jaxws-ri/extras/helidon-integration/samples/se-demo/src/main/resources/logging.properties

Integrate helidon 2.3.2, Metro 3.0.2

---

jaxws-ri/extras/helidon-integration/bom/pom.xml
jaxws-ri/extras/helidon-integration/samples/metro-samples/annotations/pom.xml
jaxws-ri/extras/helidon-integration/samples/metro-samples/annotations/src/main/resources/logging.properties
jaxws-ri/extras/helidon-integration/samples/metro-samples/async/pom.xml
jaxws-ri/extras/helidon-integration/samples/metro-samples/async/src/main/resources/logging.properties
jaxws-ri/extras/helidon-integration/samples/metro-samples/asyncprovider/src/main/resources/logging.properties
jaxws-ri/extras/helidon-integration/samples/metro-samples/asyncservice/src/main/resources/logging.properties
jaxws-ri/extras/helidon-integration/samples/metro-samples/restful/src/main/resources/logging.properties
jaxws-ri/extras/helidon-integration/samples/mp-demo/pom.xml
jaxws-ri/extras/helidon-integration/samples/mp-demo/src/main/resources/logging.properties
jaxws-ri/extras/helidon-integration/samples/se-demo/pom.xml
jaxws-ri/extras/helidon-integration/samples/se-demo/src/main/java/module-info.java
jaxws-ri/extras/helidon-integration/samples/se-demo/src/main/resources/logging.properties

Integrate Helidon 2.3.2,

---

jaxws-ri/bundles/jaxws-rt/pom.xml
jaxws-ri/bundles/jaxws-tools/pom.xml
jaxws-ri/pom.xml
jaxws-ri/runtime/policy/pom.xml
jaxws-ri/runtime/servlet/src/main/java/com/sun/xml/ws/transport/http/servlet/WSServletDelegate.java
jaxws-ri/tools/wscompile/pom.xml

exclude missing jdoc warnings

---

jaxws-ri/bundles/jaxws-ri/pom.xml
jaxws-ri/bundles/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/pom.xml
jaxws-ri/tests/pom.xml

resurrect collecting coverage data

---

jaxws-ri/bundles/jaxws-rt/pom.xml
jaxws-ri/bundles/jaxws-tools/pom.xml
jaxws-ri/bundles/pom.xml
jaxws-ri/tests/pom.xml
jaxws-ri/tests/unit/pom.xml

disable spotbugs for tests, remove obsolete profiles

---

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/util/AuthUtil.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/util/xml/XmlCatalogUtil.java

fix cp rights

---

jaxws-ri/pom.xml
jaxws-ri/runtime/rt/pom.xml

fix broken build

---

jaxws-ri/pom.xml

fix spotbugs version

---

jaxws-ri/boms/bom-ext/pom.xml
jaxws-ri/bundles/jaxws-ri/src/main/assembly/assembly.xml
jaxws-ri/bundles/jaxws-rt/pom.xml
jaxws-ri/pom.xml
jaxws-ri/runtime/rt/pom.xml

remove resolver, use angus-activation on runtime cp

use servlet 5 for now,

---

jaxws-ri/bundles/jaxws-ri/src/main/assembly/assembly.xml

fix cp right

---

jaxws-ri/boms/bom-ext/pom.xml
jaxws-ri/extras/eclipselink_jaxb/pom.xml

Integrate eclipselink 4.0.0-M1

---

jaxws-ri/runtime/httpspi-servlet/src/main/java/com/sun/xml/ws/transport/httpspi/servlet/DeploymentDescriptorParser.java
jaxws-ri/runtime/httpspi-servlet/src/main/java/com/sun/xml/ws/transport/httpspi/servlet/EndpointHttpExchange.java
jaxws-ri/runtime/rt/src/main/java/com/oracle/webservices/api/message/AccessorFactory.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/api/Component.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/fault/SOAP11Fault.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/fault/SOAP12Fault.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/fault/SOAPFaultBuilder.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/model/AbstractWrapperBeanGenerator.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/model/InjectorHelper.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/transport/http/DeploymentDescriptorParser.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/util/pipe/AbstractSchemaValidationTube.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/util/xml/StAXResult.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/wsdl/SOAPActionBasedOperationFinder.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/wsdl/WSDLOperationFinder.java

fix cprights

---

jaxws-ri/runtime/rt/src/test/java/com/sun/xml/ws/api/streaming/ContextClassloaderLocalTest.java

fix copyright

---

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/transport/http/client/HttpTransportPipe.java

add missing import

---

jaxws-ri/bundles/jaxws-rt/src/main/java/module-info.java
jaxws-ri/bundles/jaxws-tools/src/main/java/module-info.java
jaxws-ri/extras/eclipselink_jaxb/src/main/java/module-info.java
jaxws-ri/extras/eclipselink_sdo/src/main/java/module-info.java
jaxws-ri/runtime/httpspi-servlet/pom.xml
jaxws-ri/runtime/httpspi-servlet/src/main/java/module-info.java
jaxws-ri/runtime/rt/src/main/java/module-info.java
jaxws-ri/runtime/servlet/pom.xml
jaxws-ri/runtime/servlet/src/main/java/com/sun/xml/ws/transport/http/servlet/WSAsyncListener.java
jaxws-ri/runtime/servlet/src/main/java/module-info.java
jaxws-ri/tools/wscompile/src/main/java/module-info.java

fix a few modularity related warnings

---

jaxws-ri/extras/transports/async-client-transport/src/main/java/module-info.java
jaxws-ri/extras/transports/local/src/main/java/module-info.java

fix a few modularity related warnings in transports

---

jaxws-ri/runtime/rt/src/main/java/com/oracle/webservices/api/message/MessageContextFactory.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/api/message/MessageContextFactory.java

jira1077: org.jvnet.ws.message.MessageFactory.createContext(InputStream, MimeHeaders) fails

---

jaxws-ri/docs/pom.xml
jaxws-ri/pom.xml
jaxws-ri/tests/unit/pom.xml

clean up coverage setup

---

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/client/package-info.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/message/AbstractHeaderImpl.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/server/package-info.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/spi/db/OldBridge.java

Remove private contract with jaxb-ri (BridgeContext)

---

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/api/WSService.java

InitParams is used by wsit

---

jaxws-ri/extras/jaxws-maven-plugin/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/src/main/java/org/jvnet/jax_ws_commons/jaxws/AbstractJaxwsMojo.java
jaxws-ri/extras/jaxws-maven-plugin/src/main/java/org/jvnet/jax_ws_commons/jaxws/AbstractWsGenMojo.java
jaxws-ri/extras/jaxws-maven-plugin/src/main/java/org/jvnet/jax_ws_commons/jaxws/WsImportMojo.java
jaxws-ri/extras/jaxws-maven-plugin/src/test/it/jaxwscommons-43/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/src/test/it/parent/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/src/test/script/setproxy.groovy

update deps in maven plugin, move it to src/bin 11

---

jaxws-ri/bundles/jaxws-ri/src/main/resources/build.xml
jaxws-ri/docs/release-documentation/src/main/docbook/release-notes.xml
jaxws-ri/docs/release-documentation/src/main/docbook/tools-annotation-processing.xml
jaxws-ri/docs/release-documentation/src/main/docbook/tools-overview.xml
jaxws-ri/tools/wscompile/pom.xml
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/ant/WrapperTask.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/ant/WsGen2.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/ant/WsImport2.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/ant/WsTask2.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/Options.java
jaxws-ri/tools/wscompile/src/main/resources/com/sun/tools/ws/resources/wscompile.properties
jaxws-ri/tools/wscompile/src/main/resources/com/sun/tools/ws/resources/wscompile_de.properties
jaxws-ri/tools/wscompile/src/main/resources/com/sun/tools/ws/resources/wscompile_es.properties
jaxws-ri/tools/wscompile/src/main/resources/com/sun/tools/ws/resources/wscompile_fr.properties
jaxws-ri/tools/wscompile/src/main/resources/com/sun/tools/ws/resources/wscompile_it.properties
jaxws-ri/tools/wscompile/src/main/resources/com/sun/tools/ws/resources/wscompile_ja.properties
jaxws-ri/tools/wscompile/src/main/resources/com/sun/tools/ws/resources/wscompile_ko.properties
jaxws-ri/tools/wscompile/src/main/resources/com/sun/tools/ws/resources/wscompile_pt_BR.properties
jaxws-ri/tools/wscompile/src/main/resources/com/sun/tools/ws/resources/wscompile_zh_CN.properties
jaxws-ri/tools/wscompile/src/main/resources/com/sun/tools/ws/resources/wscompile_zh_TW.properties
jaxws-ri/tools/wscompile/src/test/java/com/sun/tools/ws/test/ant/AntExecutor.java
jaxws-ri/tools/wscompile/src/test/java/com/sun/tools/ws/test/ant/WsGenTaskTest.java
jaxws-ri/tools/wscompile/src/test/java/com/sun/tools/ws/test/ant/WsImportTaskTest.java
jaxws-ri/tools/wscompile/src/test/resources/com/sun/tools/ws/test/ant/resources/wsgen.xml
jaxws-ri/tools/wscompile/src/test/resources/com/sun/tools/ws/test/ant/resources/wsimport.xml

remove support for endorsed

---

jaxws-ri/docs/release-documentation/src/main/docbook/tools-wsgen-ant-task.xml
jaxws-ri/docs/release-documentation/src/main/docbook/tools-wsgen.xml
jaxws-ri/docs/release-documentation/src/main/docbook/tools-wsimport-ant-task.xml
jaxws-ri/docs/release-documentation/src/main/docbook/tools-wsimport.xml
jaxws-ri/extras/jaxws-maven-plugin/src/main/java/org/jvnet/jax_ws_commons/jaxws/AbstractJaxwsMojo.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/ant/WsTask2.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/Options.java
jaxws-ri/tools/wscompile/src/main/resources/com/sun/tools/ws/resources/wscompile.properties

add support to ant tasks and maven plugin

#299: document disableXmlSecurity flag,

---

jaxws-ri/boms/bom/pom.xml

integrate istack plugin 4.1.1

---

jaxws-ri/bundles/jaxws-rt/src/main/java/module-info.java
jaxws-ri/extras/jaxws-maven-plugin/src/main/java/org/jvnet/jax_ws_commons/jaxws/AbstractWsGenMojo.java
jaxws-ri/extras/jaxws-maven-plugin/src/main/java/org/jvnet/jax_ws_commons/jaxws/WsImportMojo.java
jaxws-ri/runtime/rt/src/main/java/module-info.java

add missing export for wsit,

---

jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/runtime/config/MetroConfig.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/runtime/config/TubeFactoryConfig.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/runtime/config/TubeFactoryList.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/runtime/config/TubelineDefinition.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/runtime/config/TubelineFeatureReader.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/runtime/config/TubelineMapping.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/runtime/config/Tubelines.java

add default constructors

---

jaxws-ri/boms/bom/pom.xml

Integrate saaj 3.0.0-M3

---

jaxws-ri/docs/release-documentation/src/main/docbook/changelog.xml
jaxws-ri/docs/release-documentation/src/main/docbook/release-notes.xml

update release docs, changelog

---

jaxws-ri/docs/release-documentation/src/main/docbook/changelog.xml
jaxws-ri/tests/unit/testcases/customization/embedded_v2/custom-client.xml
jaxws-ri/tests/unit/testcases/customization/embedded_v2/server/TestEndpoint.java
jaxws-ri/tests/unit/testcases/customization/embedded_v2/server/custom.wsdl
jaxws-ri/tests/unit/testcases/customization/embedded_v2/test-descriptor.xml
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/WsimportOptions.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wsdl/parser/DOMForest.java
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wsdl/parser/V2NSHandler.java
jaxws-ri/tools/wscompile/src/main/resources/com/sun/tools/ws/resources/configuration.properties
jaxws-ri/tools/wscompile/src/main/resources/com/sun/tools/ws/resources/wsdl.properties

Support usage of JAXWS 2.x WSDL bindings customizations

---

.github/workflows/codeql-analysis.yml
.github/workflows/maven.yml
jaxws-ri/extras/jaxws-maven-plugin/pom.xml
jaxws-ri/pom.xml
jaxws-ri/runtime/policy/pom.xml

add owasp and findsecbugs checks to the build

---

jaxws-ri/extras/jaxws-maven-plugin/src/it/jaxws-ri-samples/fromwsdl/pom.xml
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/api/streaming/XMLStreamReaderFactory.java

fix issues reported by sscan

---

.github/workflows/maven.yml
jaxws-ri/runtime/httpspi-servlet/src/main/java/com/sun/xml/ws/transport/httpspi/servlet/DeploymentDescriptorParser.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/api/streaming/XMLStreamReaderFactory.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/assembler/MetroConfigLoader.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/commons/xmlutil/Converter.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/policy/jaxws/PolicyWSDLParserExtension.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/server/EndpointFactory.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/util/xml/XmlUtil.java
jaxws-ri/runtime/rt/src/test/java/com/sun/xml/ws/util/xml/XmlUtilTest.java

#606: make XmlUtil.newXMLInputFactory consistent with other methods

---

jaxws-ri/docs/release-documentation/src/main/docbook/changelog.xml
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/spi/db/TypeInfo.java

 #596: impossible cast in spi/db/TypeInfo.java

---

jaxws-ri/boms/bom/pom.xml
jaxws-ri/extras/helidon-integration/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/pom.xml
jaxws-ri/pom.xml
jaxws-ri/runtime/policy/pom.xml

update dependencies, build plugins

---

jaxws-ri/docs/release-documentation/src/main/docbook/changelog.xml
jaxws-ri/extras/transports/local/src/main/java/com/sun/xml/ws/transport/local/LocalTransportTube.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/transport/http/HttpAdapter.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/transport/http/client/HttpTransportPipe.java
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/util/MessageWriter.java

 #542: HttpTransportPipe.dump=true freeze with binary messages

---

jaxws-ri/boms/bom/pom.xml

Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>

jakarta.annotations-api version update

---

jaxws-ri/docs/release-documentation/src/main/docbook/users-guide-overview.xml

minor tweak to documented feature list

---

.github/workflows/maven.yml
jaxws-ri/boms/bom-ext/pom.xml
jaxws-ri/boms/bom/pom.xml
jaxws-ri/docs/release-documentation/src/main/docbook/changelog.xml
jaxws-ri/extras/jaxws-maven-plugin/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/src/test/java/org/jvnet/jax_ws_commons/jaxws/MixedITCase.java
jaxws-ri/extras/jaxws-maven-plugin/src/test/java/org/jvnet/jax_ws_commons/jaxws/WsGenMojoITCase.java
jaxws-ri/extras/jaxws-maven-plugin/src/test/java/org/jvnet/jax_ws_commons/jaxws/WsImportMojoITCase.java
jaxws-ri/pom.xml
jaxws-ri/runtime/policy/pom.xml
jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/transport/http/client/HttpTransportPipe.java

#627: HttpTransportPipe dump - improve logging on empty header values

---

jaxws-ri/pom.xml

update build plugins

---

.github/workflows/maven.yml
jaxws-ri/boms/bom-ext/pom.xml
jaxws-ri/boms/bom/pom.xml

Integrate angus-activation/mail 2.0.0

---

jaxws-ri/boms/bom-ext/pom.xml
jaxws-ri/boms/bom/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/pom.xml
jaxws-ri/pom.xml
jaxws-ri/runtime/policy/pom.xml
jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/processor/modeler/annotation/WebServiceWrapperGenerator.java

Angus Mail 2.0.1
Woodstox 4.5.0

Integrate JAXB-RI 4.0.2

---

jaxws-ri/pom.xml

do not generate missing files by default

---

jaxws-ri/boms/bom-ext/pom.xml
jaxws-ri/boms/bom/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/pom.xml
jaxws-ri/pom.xml
jaxws-ri/runtime/policy/pom.xml

angus activation 2.0.1,
angus mail 2.0.2,
jakarta activation-api 2.1.2,
jakarta mail-api 2.1.2,
woodstox 6.5.1

Integrate jaxb-ri 4.0.3,

---

.github/workflows/maven.yml
jaxws-ri/boms/bom-ext/pom.xml
jaxws-ri/boms/bom/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/src/main/java/org/jvnet/jax_ws_commons/jaxws/MainWsGenMojo.java
jaxws-ri/extras/jaxws-maven-plugin/src/test/it/parent/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/src/test/java/org/jvnet/jax_ws_commons/jaxws/WsImportMojoTest.java
jaxws-ri/pom.xml
jaxws-ri/runtime/policy/pom.xml
jaxws-ri/tests/pom.xml

update build plugins,

---

jaxws-ri/docs/release-documentation/src/main/docbook/changelog.xml
jaxws-ri/extras/jaxws-maven-plugin/pom.xml
jaxws-ri/extras/jaxws-maven-plugin/src/main/java/org/jvnet/jax_ws_commons/jaxws/AbstractJaxwsMojo.java
jaxws-ri/extras/jaxws-maven-plugin/src/main/java/org/jvnet/jax_ws_commons/jaxws/AbstractWsGenMojo.java
jaxws-ri/extras/jaxws-maven-plugin/src/main/java/org/jvnet/jax_ws_commons/jaxws/MainWsGenMojo.java

#656: Perform refresh in Eclipse after M2E execution of jaxws-maven-plugin

---

.gitignore
jaxws-ri/extras/helidon-integration/se/src/main/java/org/eclipse/metro/helidon/HelidonResourceLoader.java
jaxws-ri/extras/helidon-integration/se/src/main/java/org/eclipse/metro/helidon/MetroSupport.java

https://github.com/eclipse-ee4j/metro-jax-ws/issues/681

Switch to load wsdl and schema files from multiple jars #681
